### PR TITLE
csp_io: csp_accept: Reject connection-less sockets

### LINKED ISSUE #766: csp_accept() can be called on UDP(connection-less) and RDP sockets
## Description

If a socket is marked as connection-less and `csp_accept()` is called on it, packets get interpreted as connections.

## Steps to Reproduce

Create simple server/client example, the server must be connection-less, and call `csp_accept()` on it. Once a packet arrives it will be interpreted as a connection.

## Checklist

- [x] I've searched in "Issues" for similar issues, both open and closed.
- [x] I've used GitHub Flavored Markdown (GFM) to format my text.
- [x] I've avoided using screenshots for console output or logs
- [x] I've included all relevant details and steps to reproduce the issue.
- [x] I've provided information about my environment.
- [x] I've attached necessary logs or code snippet for minimal reproducible example.

### PR DESCRIPTION
**Pull request by moonlight83340**
csp_accept() is designed for connection-oriented sockets, as it dequeues incoming connections from the socket’s receive queue.

However, connection-less sockets (CSP_SO_CONN_LESS) do not establish connections, making csp_accept() inapplicable in this context.

This commit adds an explicit check for CSP_SO_CONN_LESS in csp_accept().

If a connection-less socket is passed, the function now sets csp_dbg_errno to CSP_DBG_ERR_UNSUPPORTED and returns NULL immediately.

This prevents unintended behavior and improves API safety by ensuring csp_accept() is only used with connection-oriented sockets.

fix https://github.com/libcsp/libcsp/issues/766

ps : could use a csp_printf to make a clear message that the option connection-less is unsupported with that fonction.

### CODE REVIEW

**Comment by yashi** [comment]
I haven't look at this yet but would you mind telling me why you say "could fix" ?

**Comment by moonlight83340** [comment]
> I haven't look at this yet but would you mind telling me why you say "could fix" ?

I meant it as a way to say it fixes it, but actually, that’s not what I meant by “could.” It wasn’t meant to express a possibility, but a fact.
Sorry for the confusing English.

**Comment by yashi** [comment]
Can you post an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) which goes error with case?

File: src/csp_io.c [hunk 1]
```diff
@@ -28,6 +28,11 @@ csp_conn_t * csp_accept(csp_socket_t * sock, uint32_t timeout) {
 		csp_dbg_errno = CSP_DBG_ERR_INVALID_POINTER;
 		return NULL;
 	}
+	
+	if(sock->opts & CSP_SO_CONN_LESS) {
```
Comment (yashi) [inline src/csp_io.c]: nitpick, but you need a space between `if` and `(`.

**Comment by moonlight83340** [comment]
> Can you post an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) which goes error with case?

Okay, will do that.

**Comment by moonlight83340** [comment]
How to reproduce:

1. Apply the patch
2. Build everything with python3 ./examples/buildall.py
3. Run server and client as shown below

Here the patch to apply.
[CSP_SO_CONN_LESS.patch](https://github.com/user-attachments/files/23407768/CSP_SO_CONN_LESS.patch)

```
aetan@gaetan-ThinkPad-T16-Gen-2:~/Downloads/WIP/libcsp$ ./build/examples/csp_server -u "127.0.0.1" -a 1
Initialising CSP
  UDP peer address: 127.0.0.1:1500 (listening on port 1501)
Connection table
[00 0x632abe785ac0] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x632abe785bd0] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x632abe785ce0] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x632abe785df0] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x632abe785f00] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x632abe786010] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x632abe786120] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x632abe786230] S:0, 0 -> 0, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 14 dfl: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

UDP        addr: 1 netmask: 0 dfl: 1
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Server task started
csp_accept: csp_queue_dequeue conn : 0x632abe784690
csp_accept: csp_queue_dequeue conn : 0x632abe7847e8
csp_accept: csp_queue_dequeue conn : 0x632abe784940
csp_accept: csp_queue_dequeue conn : 0x632abe784a98
csp_accept: csp_queue_dequeue conn : 0x632abe784bf0
csp_accept: csp_queue_dequeue conn : 0x632abe784d48
csp_accept: csp_queue_dequeue conn : 0x632abe784ea0
csp_accept: csp_queue_dequeue conn : 0x632abe784ff8
csp_accept: csp_queue_dequeue conn : 0x632abe785150
csp_accept: csp_queue_dequeue conn : 0x632abe7852a8
csp_accept: csp_queue_dequeue conn : 0x632abe785400
csp_accept: csp_queue_dequeue conn : 0x632abe785558
csp_accept: csp_queue_dequeue conn : 0x632abe7856b0
```

```
gaetan@gaetan-ThinkPad-T16-Gen-2:~/Downloads/WIP/libcsp$ ./build/examples/csp_client -u "127.0.0.1" -a 2 -C 1
Initialising CSP
  UDP peer address: 127.0.0.1:1501 (listening on port 1500)
Connection table
[00 0x6234f8a66aa0] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x6234f8a66bb0] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x6234f8a66cc0] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x6234f8a66dd0] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x6234f8a66ee0] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x6234f8a66ff0] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x6234f8a67100] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x6234f8a67210] S:0, 0 -> 0, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 14 dfl: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

UDP        addr: 2 netmask: 0 dfl: 1
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Client started
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
Ping address: 1, result -1 [mS]
reboot system request sent to address: 1
```

If we remove : `sock.opts = CSP_SO_CONN_LESS;` from the csp_server we got :

```
gaetan@gaetan-ThinkPad-T16-Gen-2:~/Downloads/WIP/libcsp$ ./build/examples/csp_server -u "127.0.0.1" -a 1
Initialising CSP
  UDP peer address: 127.0.0.1:1500 (listening on port 1501)
Connection table
[00 0x598706fc4ac0] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x598706fc4bd0] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x598706fc4ce0] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x598706fc4df0] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x598706fc4f00] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x598706fc5010] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x598706fc5120] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x598706fc5230] S:0, 0 -> 0, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 14 dfl: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

UDP        addr: 1 netmask: 0 dfl: 1
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Server task started
csp_accept: csp_queue_dequeue conn : 0x598706fc4bd0
csp_accept: csp_queue_dequeue conn : 0x598706fc4ce0
csp_accept: csp_queue_dequeue conn : 0x598706fc4df0
Packet received on SERVER_PORT: Hello world A
csp_accept: csp_queue_dequeue conn : 0x598706fc4f00
csp_accept: csp_queue_dequeue conn : 0x598706fc5010
csp_accept: csp_queue_dequeue conn : 0x598706fc5120
Packet received on SERVER_PORT: Hello world B
csp_accept: csp_queue_dequeue conn : 0x598706fc5230
csp_accept: csp_queue_dequeue conn : 0x598706fc4ac0
csp_accept: csp_queue_dequeue conn : 0x598706fc4bd0
Packet received on SERVER_PORT: Hello world C
csp_accept: csp_queue_dequeue conn : 0x598706fc4ce0
csp_accept: csp_queue_dequeue conn : 0x598706fc4df0
csp_accept: csp_queue_dequeue conn : 0x598706fc4f00
Packet received on SERVER_PORT: Hello world D
csp_accept: csp_queue_dequeue conn : 0x598706fc5010
csp_accept: csp_queue_dequeue conn : 0x598706fc5120
csp_accept: csp_queue_dequeue conn : 0x598706fc5230
Packet received on SERVER_PORT: Hello world E
csp_accept: csp_queue_dequeue conn : 0x598706fc4ac0
csp_accept: csp_queue_dequeue conn : 0x598706fc4bd0
csp_accept: csp_queue_dequeue conn : 0x598706fc4ce0
Packet received on SERVER_PORT: Hello world F
csp_accept: csp_queue_dequeue conn : 0x598706fc4df0
csp_accept: csp_queue_dequeue conn : 0x598706fc4f00
csp_accept: csp_queue_dequeue conn : 0x598706fc5010
Packet received on SERVER_PORT: Hello world G
csp_accept: csp_queue_dequeue conn : 0x598706fc5120
csp_accept: csp_queue_dequeue conn : 0x598706fc5230
csp_accept: csp_queue_dequeue conn : 0x598706fc4ac0
Packet received on SERVER_PORT: Hello world H
csp_accept: csp_queue_dequeue conn : 0x598706fc4bd0
csp_accept: csp_queue_dequeue conn : 0x598706fc4ce0
csp_accept: csp_queue_dequeue conn : 0x598706fc4df0
Packet received on SERVER_PORT: Hello world I
csp_accept: csp_queue_dequeue conn : 0x598706fc4f00
csp_accept: csp_queue_dequeue conn : 0x598706fc5010
csp_accept: csp_queue_dequeue conn : 0x598706fc5120
Packet received on SERVER_PORT: Hello world J
```

```
gaetan@gaetan-ThinkPad-T16-Gen-2:~/Downloads/WIP/libcsp$ ./build/examples/csp_client -u "127.0.0.1" -a 2 -C 1
Initialising CSP
  UDP peer address: 127.0.0.1:1501 (listening on port 1500)
Connection table
[00 0x5aaa5f25eaa0] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x5aaa5f25ebb0] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x5aaa5f25ecc0] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x5aaa5f25edd0] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x5aaa5f25eee0] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x5aaa5f25eff0] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x5aaa5f25f100] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x5aaa5f25f210] S:0, 0 -> 0, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 14 dfl: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

UDP        addr: 2 netmask: 0 dfl: 1
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Client started
Ping address: 1, result 0 [mS]
reboot system request sent to address: 1
Ping address: 1, result 0 [mS]
reboot system request sent to address: 1
Ping address: 1, result 1 [mS]
reboot system request sent to address: 1
Ping address: 1, result 1 [mS]
reboot system request sent to address: 1
Ping address: 1, result 1 [mS]
reboot system request sent to address: 1
Ping address: 1, result 0 [mS]
reboot system request sent to address: 1
Ping address: 1, result 0 [mS]
reboot system request sent to address: 1
Ping address: 1, result 1 [mS]
reboot system request sent to address: 1
Ping address: 1, result 1 [mS]
reboot system request sent to address: 1
Ping address: 1, result 1 [mS]
reboot system request sent to address: 1
```

If a socket is marked as connection-less and csp_accept() is called on it, packets get interpreted as connections.

i hope everything is clear.

**Comment by yashi** [comment]
@moonlight83340 Please add a commit for a CHANGELOG entry.
